version: '3.8'

services:
  db:
    build: ./database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
   
  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:password@db:5432/desk_booking_db_testing

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend