name: CI/CD

on:
  pull_request:
    branches: [master]

env:
  VERSION: 0.1.0

jobs:
  Test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build container for tests
      run: docker compose build

    - name: Run backend tests
      run: docker-compose run backend pytest

    - name: Run frontend tests
      run: docker-compose run frontend npm test

  Lint:
    name: Lint both frontend and backend
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{js,jsx,ts,tsx,md}
          
      - name: Check files using the black formatter
        uses: psf/black@stable
        with:
          src: "./backend"