name: Weekly Vulnerability Scan

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1"

jobs:
  VulnScanFrontend:
    name: Frontend - Vulnerability Scan

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm i --package-lock-only
      - uses: oke-py/npm-audit-action@v2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: ./frontend

  VulnScanBackend:
    name: Backend - Vulnerability Scan

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - uses: pypa/gh-action-pip-audit@v1.0.6
        with:
          inputs: ./backend/requirements.txt
